apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepmimo-scenarios
  namespace: kubeflow
  labels:
    app: deepmimo
    component: scenarios
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
