apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepmimo-artifacts
  namespace: kubeflow
  labels:
    app: deepmimo
    component: artifacts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
